name: "Frogbot SCA + SAST PR Workflow"
on:
  pull_request_target:
    types: [opened, synchronize]

  # ✅ Allow manual triggering from GitHub Actions tab
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write # For OIDC authentication

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Scan against main branch
        branch: ["main"]

    steps:
      # ✅ Checkout code (shallow clone is fine since we're setting JF_GIT_BASE_BRANCH)
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Run Frogbot with Separate PRs for SCA Fixes
      - name: Frogbot - Separate SCA Fix PRs
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://${{ vars.JF_URL }}/

          # GitHub token
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Dynamically set the base branch for PR scans
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref || matrix.branch }}

          # SCA auto-remediation enabled (creates individual PRs)
          JF_GIT_AGGREGATE_FIXES: "FALSE"
          JF_FIXABLE_ONLY: "TRUE"
          JF_SCAN: "sca"

        with:
          oidc-provider-name: frogbot

      # ✅ Run Frogbot with Aggregated SCA Fix PR
      - name: Frogbot - Aggregated SCA Fix PR
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref || matrix.branch }}

          # Aggregate all fixes into a single PR
          JF_GIT_AGGREGATE_FIXES: "TRUE"
          JF_FIXABLE_ONLY: "TRUE"
          JF_SCAN: "sca"

        with:
          oidc-provider-name: frogbot

      # ✅ Run Frogbot for SAST Scan (no auto-fix, add PR comments)
      - name: Frogbot - SAST Scan
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref || matrix.branch }}

          # Enable SAST scanning
          JF_SCAN: "sast"

          # Fail workflow on High/Critical SAST issues
          JF_MIN_SEVERITY: "High"
          JF_FIXABLE_ONLY: "FALSE"
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
          JF_AVOID_PREVIOUS_PR_COMMENTS_DELETION: "TRUE"

        with:
          oidc-provider-name: frogbot
